### ISSUE TITLE
ROS groovy rosjava_test:CompileJava "test_ros package does not exist" 

### ISSUE THREAD

**Issue by HenryWilliams** [rosjava/rosjava_core#156] opened 2013-05-01 01:57 UTC
What steps will reproduce the problem?
Download rosjava_core into "~/catking_ws/src"
Run catkin_make in "~/catkin_ws"

What is the expected output? What do you see instead?
Expected: rosjava_core builds successfully

Instead: Builds successfully until "rosjava_test:ComplieJava"
Error: ../rosjava_core/rosjava_test/src/main/java/org/ros/ParameterServerTestNode.java:58 package ros_test does not exist"

What version of the product are you using? On what operating system?
ROS Groovy Ubunutu 12.04 Latest rosjava_core from this Git repo
Java JDK 7 64 bit latest release

Please provide any additional information below.
I can manually find the ros_test folder within rosjava_bootstrapping/src/test/resources/test_ros.

**Comment by damonkohler** [comment] 2013-05-15 06:54
I can't reproduce this issue. Make sure you've installed the test_ros package normally (e.g. apt-get) and that it's in your ROS_PACKAGE_PATH. It does not belong in the rosjava_core stack.

**Comment by amanciodiaz** [comment] 2013-05-25 10:37
I found the same issue. The problem is out of date documentation. There is a recent pull request https://github.com/rosjava/rosjava_core/pull/162 that solves the problem

**Comment by HenryWilliams** [comment] 2013-05-25 10:44
Cool, thanks for that, will give it a go tomorrow :D 

Cheers

**Comment by jmtatsch** [comment] 2013-05-31 15:05
What can i do on osx? There is no apt-get to:
sudo apt-get install python-rosinstall

**Comment by stonier** [comment] 2013-08-28 14:17
Actually, should be using wstool with catkin. On osx I believe you can still use pip to get rosinstall, rosws, wstool.

Closing this - documentation updates are ticketed by #168

**Closed as completed by stonier** 2013-08-28 14:17 UTC
